apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lb-argocd
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated: 
      selfHeal: true
      prune: true
  source:
    repoURL: https://github.com/Riukotashi/container-argocd.git
    targetRevision: HEAD
    path: load-balancer
  destination:
    server: https://kubernetes.default.svc
    namespace: default